Repository L-Carr/Platoon-Console, pull requests merged in 2024-05, with the labels that each got.

#99 96 build attendance component
  frontend/platoon-console/src/components/Accountability.jsx
  frontend/platoon-console/src/custom.scss
  frontend/platoon-console/src/pages/Homepage.jsx
  frontend/platoon-console/src/pages/Login.jsx
Labels: enhancement

#124 10 build demo slot component
  frontend/platoon-console/src/components/Demo.jsx
  frontend/platoon-console/src/custom.scss
  frontend/platoon-console/src/pages/DemoPage.jsx
  frontend/platoon-console/src/pages/Homepage.jsx
  frontend/platoon-console/src/pages/VideoGallery.jsx
  frontend/platoon-console/src/router.jsx
Labels: help wanted

#126 Refactored Demo to match RollCall
  frontend/platoon-console/src/components/Demo.jsx
  frontend/platoon-console/src/custom.scss
Labels: enhancement

#153 152 remove ssl frontend change backend links from https to http
  frontend/platoon-console/src/components/Accountability.jsx
  frontend/platoon-console/src/components/Demo.jsx
  frontend/platoon-console/src/components/Groupings.jsx
  frontend/platoon-console/src/components/RollCall.jsx
  frontend/platoon-console/src/components/StudentAttCard.jsx
  frontend/platoon-console/src/pages/ChangePassword.jsx
  frontend/platoon-console/src/pages/ForgotPassword.jsx
  frontend/platoon-console/src/pages/Homepage.jsx
  frontend/platoon-console/src/pages/Login.jsx
  frontend/platoon-console/src/pages/Register.jsx
  frontend/platoon-console/src/pages/VideoGallery.jsx
Labels: bug

#156 89 cypress testing for frontend
  frontend/platoon-console/cypress.config.js
  frontend/platoon-console/cypress/e2e/01-navbar.cy.js
  frontend/platoon-console/cypress/e2e/02-register.cy.js
  frontend/platoon-console/cypress/e2e/03-login.cy.js
  frontend/platoon-console/cypress/e2e/04-homepage.cy.js
  frontend/platoon-console/cypress/fixtures/example.json
  frontend/platoon-console/cypress/support/commands.js
  frontend/platoon-console/cypress/support/e2e.js
  frontend/platoon-console/package-lock.json
  frontend/platoon-console/package.json
  frontend/platoon-console/src/components/NavBar.jsx
Labels: question

#161 153 canvas
  frontend/platoon-console/package-lock.json
  frontend/platoon-console/package.json
  frontend/platoon-console/src/pages/CanvasPage.css
  frontend/platoon-console/src/pages/CanvasPage.jsx
  frontend/platoon-console/src/pages/Homepage.jsx
  frontend/platoon-console/src/router.jsx
Labels: enhancement

#163 Fixed card > Card
  frontend/platoon-console/src/components/Github.jsx
Labels: bug
